[package]
name = "slashstep_server_resources"
version = "0.1.0"
edition = "2024"
description = "Required resources for a Slashstep server."
readme = "README.md"
homepage = "https://slashstep.com"
repository = "https://github.com/SlashstepGroup/server"
license = "MPL-2.0"
keywords = ["project management", "problem management", "issue tracking"]
publish = false

[dependencies]
pg_escape = "0.1.1"
postgres = { version = "0.19.12", features = ["with-uuid-1"] }
postgres-types = { version = "0.2.11", features = ["derive"] }
regex = "1.12.2"
uuid = { version = "1.18.1", features = ["v7"] }

[dev-dependencies]
testcontainers = { version = "0.25.2", features = ["blocking"] }
testcontainers-modules = { version = "0.13.0", features = ["postgres"] }
