# This workflow is used to bypass the Rust tests on pull requests if no code was changed.
# This hack is necessary because GitHub Actions doesn't currently support skipping required tests.

name: Bypass Rust tests
on:
  pull_request:
    paths-ignore: 
      - src/**
      - Cargo.toml
      - Cargo.lock
      - .github/workflows/run-rust-tests-on-development-environment.yml
      - .github/workflows/run-rust-tests-on-pull-request.yml
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Test pull request # This needs to be the same name as the one in run-rust-tests.yml.
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "No Rust code or workflows were changed, so testing may not be required."'
