# This workflow is used to bypass the Rust tests on pull requests if no code was changed.
# This hack is necessary because GitHub Actions doesn't currently support skipping required tests.

name: Run Rust tests # This needs to be the same name as the one in run-rust-tests.yml.
on:
  pull_request:
    paths-ignore: 
      - src/**
      - Cargo.toml
      - Cargo.lock
      - .github/workflows/run-rust-tests.yml
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "No code was changed, so testing is not required."'