name: Run Rust tests
on:
  push:
    paths:
      - src/**
      - Cargo.toml
      - Cargo.lock
      - .github/workflows/run-rust-tests.yml
    branches:
      - main
  pull_request:
    paths: 
      - src/**
      - Cargo.toml
      - Cargo.lock
      - .github/workflows/run-rust-tests.yml
  workflow_dispatch:

jobs:
  test:
    name: cargo test
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v6.0.0
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - run: mkdir secrets
      - run: openssl genrsa -out secrets/jwt-private-key.pem 2048
      - run: openssl rsa -in secrets/jwt-private-key.pem -pubout -out ./secrets/jwt-public-key.pem
      - run: RUSTFLAGS="-Awarnings" cargo test --all-features
        env:
          JWT_PUBLIC_KEY_PATH: ./secrets/jwt-public-key.pem
          JWT_PRIVATE_KEY_PATH: ./secrets/jwt-private-key.pem
